package Anon.controller.service.core.handler.subhandler;

import Anon.controller.service.core.handler.MessageHandlerInterface;
import Anon.controller.service.message.AnonMessage;

import java.util.HashMap;

/**
 * <p>
 * The class handles the local network operators' commands.
 * The commands usually handle debugging tasks for Anon.
 */
public class AdminHandler implements MessageHandlerInterface {

    /**
     * Contructor function: set the reference of Anon Intelligence to the actual object
     */
    public AdminHandler() {
    }

    /**
     * handle messages from the local operators. Currently empty.
     *
     * @param msg the Anon messages generated by the local admin
     * @return a hashmap of message return status
     */
    @Override
    public HashMap handleMessage(AnonMessage msg) {

        return null;
    }
}
